# Generated by Django 3.1.5 on 2021-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id_devis', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nom_devis', models.CharField(max_length=60)),
            ],
        ),
    ]
