# Generated by Django 3.1.5 on 2021-02-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_MADERA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='composants',
        ),
        migrations.CreateModel(
            name='ModuleComposant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_REST_MADERA.composant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_REST_MADERA.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='composants',
            field=models.ManyToManyField(through='API_REST_MADERA.ModuleComposant', to='API_REST_MADERA.Composant'),
        ),
    ]
