# Generated by Django 3.1.5 on 2021-02-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_MADERA', '0002_auto_20210206_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecomposant',
            name='composant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity', to='API_REST_MADERA.composant'),
        ),
    ]
