# Generated by Django 3.1.5 on 2021-01-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_MADERA', '0002_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user_be',
        ),
    ]
