# Generated by Django 3.1.5 on 2021-02-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_MADERA', '0002_auto_20210207_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='state',
            field=models.CharField(choices=[('En attente', 'Enattente'), ('Accepté', 'Accepte'), ('Refusé', 'Refuse')], default='En attente', max_length=20),
        ),
    ]
