# Generated by Django 3.1.5 on 2021-02-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_MADERA', '0003_devis_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devis',
            old_name='state',
            new_name='etat',
        ),
    ]
