# Generated by Django 3.1.5 on 2021-02-06 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_MADERA', '0003_auto_20210206_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecomposant',
            name='composant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_REST_MADERA.composant'),
        ),
    ]
