# Generated by Django 3.1.5 on 2021-02-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_MADERA', '0004_auto_20210207_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='gamme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API_REST_MADERA.gamme'),
        ),
    ]
