# Generated by Django 3.1.5 on 2021-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_erp', '0002_internaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='department',
            field=models.CharField(choices=[('BE', 'BE'), ('Commercial', 'Commercial'), ('Administrator', 'Administrator')], default='Commercial', max_length=25),
        ),
    ]
